# Generated by Django 4.1.7 on 2023-04-09 05:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitulo')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción del producto')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount', models.SmallIntegerField(default=0, verbose_name='Cantidad almacen')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['order', 'title'],
            },
        ),
    ]
